apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-analyzer
spec:
  selector:
    matchLabels:
      app: text-analyzer
  template:
    metadata:
      labels:
        app: text-analyzer
    spec:
      containers:
        - name: text-analyzer
          image: lorenzobacchiani/no-mcl
          imagePullPolicy: Always
          ports:
            - containerPort: 8014
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: MCL
              value: "120"
            - name: LIMIT
              value: "1000"
            - name: BATCH
              value: "200"
            - name: SERVICE
              value: "text-analyzer"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: text-analyzer-service
spec:
  selector:
    app: text-analyzer
  ports:
    - protocol: TCP
      port: 8014
      targetPort: 8014

