version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  monitor:
    build:
      context: ./monitor
    ports:
      - "3200:3200"
    environment:
      - BATCH_SIZE=50
      - RECORD_NUMBER=10

  entrypoint:
    build:
      context: ./entrypoint
    ports:
      - "8010:8010"
    environment:
        - HOSTNAME=rabbitmq
        - DB_URL=http://monitor:3200
        - REFRESH_TIME=1000
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  parser:
    build:
      context: ./parser
    ports:
      - "8011:8011"
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://monitor:3200
      - MCL=110
    depends_on:
      - rabbitmq
      - monitor
      - entrypoint
    links:
      - rabbitmq
      - monitor
      - entrypoint

  virus-scanner:
    build:
      context: ./virus-scanner
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://monitor:3200
      - MCL=120
    depends_on:
      - rabbitmq
      - monitor
      - parser
    links:
      - rabbitmq
      - monitor
      - parser

  attachment-manager:
    build:
      context: ./attachment-manager
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://monitor:3200
      - MCL=231
    depends_on:
      - rabbitmq
      - monitor
      - virus-scanner
    links:
      - rabbitmq
      - monitor
      - virus-scanner

  image-analyzer:
    build:
      context: ./image-analyzer
    ports:
      - "8003:8003"
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://monitor:3200
      - MCL=231
    depends_on:
      - rabbitmq
      - monitor
      - attachment-manager
    links:
      - rabbitmq
      - monitor
      - attachment-manager

  image-recognizer:
    build:
      context: ./image-recognizer
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://monitor:3200
      - MCL=90
    depends_on:
      - rabbitmq
      - monitor
      - image-analyzer
    links:
      - rabbitmq
      - monitor
      - image-analyzer

  nswf-detector:
    build:
      context: ./nsfw-detector
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://monitor:3200
      - MCL=90
    depends_on:
      - rabbitmq
      - monitor
      - image-analyzer
    links:
      - rabbitmq
      - monitor
      - image-analyzer

  message-analyzer:
    build:
      context: ./message-analyzer
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://monitor:3200
      - MCL=300
    depends_on:
        - rabbitmq
        - monitor
        - virus-scanner
    links:
      - rabbitmq
      - monitor
