version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    build:
      context: ./database
    ports:
      - "3200:3200"

  entrypoint:
    build:
      context: ./entrypoint
    ports:
      - "8010:8010"
    environment:
        - HOSTNAME=rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  parser:
    build:
      context: ./parser
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://database:3200
    depends_on:
      - rabbitmq
      - database
      - entrypoint
    links:
      - rabbitmq
      - database
      - entrypoint

  virus-scanner:
    build:
      context: ./virus-scanner
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://database:3200
    depends_on:
      - rabbitmq
      - database
      - parser
    links:
      - rabbitmq
      - database
      - parser

  attachment-manager:
    build:
      context: ./attachment-manager
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://database:3200
    depends_on:
      - rabbitmq
      - database
      - virus-scanner
    links:
      - rabbitmq
      - database
      - virus-scanner

  image-analyzer:
    build:
      context: ./image-analyzer
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://database:3200
    depends_on:
      - rabbitmq
      - database
      - attachment-manager
    links:
      - rabbitmq
      - database
      - attachment-manager

  image-recognizer:
    build:
      context: ./image-recognizer
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://database:3200
    depends_on:
      - rabbitmq
      - database
      - image-analyzer
    links:
      - rabbitmq
      - database
      - image-analyzer

  nswf-detector:
    build:
      context: ./nsfw-detector
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://database:3200
    depends_on:
      - rabbitmq
      - database
      - image-analyzer
    links:
      - rabbitmq
      - database
      - image-analyzer

  message-analyzer:
    build:
      context: ./message-analyzer
    environment:
      - HOSTNAME=rabbitmq
      - DB_URL=http://database:3200
    depends_on:
        - rabbitmq
        - database
        - virus-scanner
    links:
      - rabbitmq
      - database



