apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-recognizer
spec:
  selector:
    matchLabels:
      app: image-recognizer
  template:
    metadata:
      labels:
        app: image-recognizer
    spec:
      containers:
        - name: image-recognizer
          image: lorenzobacchiani/image-recognizer
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: MCL
              value: "90"
            - name: LIMIT
              value: "50"
            - name: BATCH
              value: "85"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: image-recognizer-service
spec:
  selector:
    app: image-recognizer
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004

