apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment-manager
spec:
  selector:
    matchLabels:
      app: attachment-manager
  template:
    metadata:
      labels:
        app: attachment-manager
    spec:
      containers:
        - name: attachment-manager
          image: giovaz94/attachment-manager-service:development
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: HOSTNAME
              value: "rabbitmq-service"
            - name: RABBITMQ_USERNAME
              value: "pipeline_broker"
            - name: RABBITMQ_PASSWORD
              value: "p1p3l1n3"
            - name: RABBITMQ_VHOST
              value: "pipeline-vhost"
            - name: QUEUE_NAME
              value: "attachmentman.queue"
            - name: DB_URL
              value: "http://monitor-service:3200"
            - name: MCL
              value: "231"
            - name: PREFETCH
              value: "231"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: attachment-manager-service
spec:
  selector:
    app: attachment-manager
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

