apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment-manager
spec:
  selector:
    matchLabels:
      app: attachment-manager
  template:
    metadata:
      labels:
        app: attachment-manager
    spec:
      containers:
        - name: attachment-manager
          image: lorenzobacchiani/attachment-manager
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: MCL
              value: "231"
            - name: REDIS_HOST
              value: "redis-service"
            - name: LIMIT
              value: "400"
            - name: BATCH
              value: "231"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: attachment-manager-service
spec:
  selector:
    app: attachment-manager
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

