---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-attachment-manager
spec:
  selector:
    matchLabels:
      app: ls-algorithm-attachment-manager
  template:
    metadata:
      labels:
        app: ls-algorithm-attachment-manager
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling:development
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          env:
            - name: SLEEP_TIME
              value: "2"
            - name: COMPONENT_MCL
              value: "231"
            - name: COMPONENT_MF
              value: "1.5"
            - name: K_BIG
              value: "10"
            - name: K
              value: "1"
            - name: MONITOR_URL
              value: "http://attachment-manager-service:8002"
            - name: MANIFEST_NAME
              value: "attachment-manager"
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-attachment-manager-service
spec:
  selector:
    app: ls-algorithm-attachment-manager
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
