apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-analyzer
spec:
  selector:
    matchLabels:
      app: header-analyzer
  template:
    metadata:
      labels:
        app: header-analyzer
    spec:
      containers:
        - name: header-analyzer
          image: lorenzobacchiani/no-mcl
          imagePullPolicy: Always
          ports:
            - containerPort: 9012
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: LIMIT
              value: "800"
            - name: PORT
              value: "9012"
            - name: BATCH
              value: "2000"
            - name: SERVICE
              value: "header-analyzer"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: header-analyzer-service
spec:
  selector:
    app: header-analyzer
  ports:
    - protocol: TCP
      port: 9012
      targetPort: 9012

