---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-parser
spec:
  selector:
    matchLabels:
      app: ls-algorithm-parser
  template:
    metadata:
      labels:
        app: ls-algorithm-parser
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "110"
            - name: COMPONENT_MF
              value: "1.0"
            - name: K_BIG
              value: "20"
            - name: K
              value: "10"
            - name: MANIFEST_NAME
              value: "parser"
            - name: METRIC_NAME
              value: "http_requests_total_parser"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name:  SERVICE_PORT
              value: "7000"
            - name: ORACLE
              value: "false"
            - name: PREDICTIONS
              value: "11.11111111111111, 127.77777777777779, 330.0, 1643.3333333333335, 5858.88888888889, 5333.333333333334, 5800.0, 7428.88888888889, 7286.666666666667, 6052.222222222223, 5186.666666666667, 4445.555555555556, 3565.5555555555557, 3360.0, 3344.444444444445, 3066.666666666667, 2432.222222222222, 2430.0, 831.1111111111112, 1225.5555555555557"


---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-parser-service
spec:
  selector:
    app: ls-algorithm-parser
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
