---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-parser
spec:
  selector:
    matchLabels:
      app: ls-algorithm-parser
  template:
    metadata:
      labels:
        app: ls-algorithm-parser
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "110"
            - name: COMPONENT_MF
              value: "1.0"
            - name: K_BIG
              value: "20"
            - name: K
              value: "10"
            - name: MANIFEST_NAME
              value: "parser"
            - name: METRIC_NAME
              value: "http_requests_total_parser"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name:  SERVICE_PORT
              value: "7000"
            - name: ORACLE
              value: "true"
            - name: PREDICTIONS
              value: "153, 417, 1986, 5913, 5908, 5930, 7416, 7293, 5979, 5178, 4396, 3549, 3011, 3007, 3027, 2436, 1954, 798, 1503, 4455"


---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-parser-service
spec:
  selector:
    app: ls-algorithm-parser
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
