---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-parser
spec:
  selector:
    matchLabels:
      app: ls-algorithm-parser
  template:
    metadata:
      labels:
        app: ls-algorithm-parser
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling:development
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: SLEEP_TIME
              value: "2"
            - name: COMPONENT_MCL
              value: "70"
            - name: COMPONENT_MF
              value: "1.0"
            - name: K_BIG
              value: "20"
            - name: K
              value: "4"
            - name: MONITOR_URL
              value: "http://entrypoint-service:8010"
            - name: DB_URL
              value: "http://monitor-service:3200"
            - name: MANIFEST_NAME
              value: "parser"
            - name: INBOUND_WORKLOAD_METRIC
              value: "http_requests_total_parser"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name:  SERVICE_PORT
              value: "7000"


---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-parser-service
spec:
  selector:
    app: ls-algorithm-parser
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
