apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
spec:
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: giovaz94/parser-service:development
          imagePullPolicy: Always
          ports:
            - containerPort: 8011
          env:
            - name: HOSTNAME
              value: "rabbitmq-service"
            - name: RABBITMQ_USERNAME
              value: "pipeline_broker"
            - name: RABBITMQ_PASSWORD
              value: "p1p3l1n3"
            - name: RABBITMQ_VHOST
              value: "pipeline-vhost"
            - name: QUEUE_NAME
              value: "parser.queue"
            - name: DB_URL
              value: "http://monitor-service:3200"
            - name: REDIS_HOST
              value: "redis-service"
            - name: MCL
              value: "110"
            - name: PREFETCH
              value: "90"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: parser-service
spec:
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011

