apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
spec:
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: giovaz94/parser-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8011
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: MCL
              value: "110"
            - name: LIMIT
              value: "20000"
            - name: DELAY
              value: "700"
            - name: BATCH
              value: "110"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: parser-service
spec:
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011

