---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-nsfw-detector
spec:
  selector:
    matchLabels:
      app: ls-algorithm-nsfw-detector
  template:
    metadata:
      labels:
        app: ls-algorithm-nsfw-detector
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling:development
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          env:
            - name: SLEEP_TIME
              value: "2"
            - name: COMPONENT_MCL
              value: "90"
            - name: COMPONENT_MF
              value: "1.5"
            - name: K_BIG
              value: "10"
            - name: K
              value: "1"
            - name: MONITOR_URL
              value: "http://nsfw-detector-service:8005"
            - name: MANIFEST_NAME
              value: "nsfw-detector"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-nsfw-detector-service
spec:
  selector:
    app: ls-algorithm-nsfw-detector
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
