apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsfw-detector
spec:
  selector:
    matchLabels:
      app: nsfw-detector
  template:
    metadata:
      labels:
        app: nsfw-detector
    spec:
      containers:
        - name: nsfw-detector
          image: giovaz94/nsfw-detector-service:development
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: HOSTNAME
              value: "rabbitmq-service"
            - name: RABBITMQ_USERNAME
              value: "pipeline_broker"
            - name: RABBITMQ_PASSWORD
              value: "p1p3l1n3"
            - name: RABBITMQ_VHOST
              value: "pipeline-vhost"
            - name: QUEUE_NAME
              value: "nsfwdet.queue"
            - name: DB_URL
              value: "http://monitor-service:3200"
            - name: MCL
              value: "90"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nsfw-detector-service
spec:
  selector:
    app: nsfw-detector
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP

