apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsfw-detector
spec:
  selector:
    matchLabels:
      app: nsfw-detector
  template:
    metadata:
      labels:
        app: nsfw-detector
    spec:
      containers:
        - name: nsfw-detector
          image: lorenzobacchiani/nsfw-detector
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: MCL
              value: "90"
            - name: LIMIT
              value: "400"
            - name: BATCH
              value: "85"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nsfw-detector-service
spec:
  selector:
    app: nsfw-detector
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP

