apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  labels:
    app: entrypoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entrypoint
  template:
    metadata:
      labels:
        app: entrypoint
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: entrypoint
          image: giovaz94/entrypoint:development
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          env:
            - name: DB_URL
              value: "http://monitor-service:3200"
            - name: HOSTNAME
              value: "rabbitmq-service"
            - name: PORT
              value: "8010"
            - name: RABBITMQ_USERNAME
              value: "pipeline_broker"
            - name: RABBITMQ_PASSWORD
              value: "p1p3l1n3"
            - name: RABBITMQ_VHOST
              value: "pipeline-vhost"
            - name: EXCHANGE_NAME
              value: "pipeline.direct"
            - name: QUEUE_TYPE
              value: "parser.req"
            - name: REFRESH_TIME
              value: "300000"
            - name: LS_ENABLED
              value: "true"
          resources:
            requests:
              cpu: 100m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: entrypoint
  name: entrypoint-service
spec:
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      nodePort: 30080
  selector:
    app: entrypoint
  type: NodePort