apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-attachment-manager-
  labels:
    app: attachment-manager
spec:
  containers:
  - name: parser
    image: giovaz94/attachment-manager-service:development
