apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-image-analyzer-
spec:
  containers:
  - name: parser
    image: giovaz94/image-analyzer-service:development
    env:
      - name: HOSTNAME
        value: "rabbitmq-service"
      - name: RABBITMQ_USERNAME
        value: "pipeline_broker"
      - name: RABBITMQ_PASSWORD
        value: "p1p3l1n3"
      - name: REDIS_HOST
        value: "redis-service"
      - name: RABBITMQ_VHOST
        value: "pipeline-vhost"
      - name: QUEUE_NAME
        value: "imageanalyzer.queue"
      - name: DB_URL
        value: "http://monitor-service:3200"
      - name: MCL
        value: "231"
