---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-virus-scanner
spec:
  selector:
    matchLabels:
      app: ls-algorithm-virus-scanner
  template:
    metadata:
      labels:
        app: ls-algorithm-virus-scanner
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling
          imagePullPolicy: Always
          ports:
            - containerPort: 7006
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "120"
            - name: COMPONENT_MF
              value: "2.0"
            - name: K_BIG
              value: "20"
            - name: K
              value: "10"
            - name: MANIFEST_NAME
              value: "virus-scanner"
            - name: METRIC_NAME
              value: "http_requests_total_virus_scanner_counter"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: IN_CLUSTER
              value: "true"
            - name: SERVICE_PORT
              value: "7006"
            - name: ORACLE
              value: "false"
            - name: PREDICTIONS
              value: "20.129444444444445, 337.77777777777777, 690.0, 1667.7777777777778, 3863.1111111111113, 8176.289, 13978.88888888889, 14489.943004964069, 17497.921191323036, 18613.13771257086, 10141.111111111111, 8784.525656902731, 7017.046340545137, 6677.72, 6232.222222222223, 6260.0, 4982.222222222223, 4897.777777777777, 1838.8888888888887, 2026.6666666666667"
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-virus-scanner-service
spec:
  selector:
    app: ls-algorithm-virus-scanner
  ports:
    - protocol: TCP
      port: 7006
      targetPort: 7006
