---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-virus-scanner
spec:
  selector:
    matchLabels:
      app: ls-algorithm-virus-scanner
  template:
    metadata:
      labels:
        app: ls-algorithm-virus-scanner
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling:development
          imagePullPolicy: Always
          ports:
            - containerPort: 7006
          env:
            - name: SLEEP_TIME
              value: "2"
            - name: COMPONENT_MCL
              value: "110"
            - name: COMPONENT_MF
              value: "1.0"
            - name: K_BIG
              value: "10"
            - name: K
              value: "1"
            - name: MONITOR_URL
              value: "http://virus-scanner-service:8001"
            - name: MANIFEST_NAME
              value: "virus-scanner"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-virus-scanner-service
spec:
  selector:
    app: ls-algorithm-virus-scanner
  ports:
    - protocol: TCP
      port: 7006
      targetPort: 7006
