apiVersion: apps/v1
kind: Deployment
metadata:
  name: virus-scanner
spec:
  selector:
    matchLabels:
      app: virus-scanner
  template:
    metadata:
      labels:
        app: virus-scanner
    spec:
      containers:
        - name: virus-scanner
          image: giovaz94/virus-scanner-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: MCL
              value: "120"
            - name: REDIS_HOST
              value: "redis-service"
            - name: LIMIT
              value: "500"
            - name: DELAY
              value: "900"
            - name: BATCH
              value: "120"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: virus-scanner-service
spec:
  selector:
    app: virus-scanner
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

