---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-image-analyzer
spec:
  selector:
    matchLabels:
      app: ls-algorithm-image-analyzer
  template:
    metadata:
      labels:
        app: ls-algorithm-image-analyzer
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling:development
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7002
          env:
            - name: SLEEP_TIME
              value: "2"
            - name: COMPONENT_MCL
              value: "231"
            - name: COMPONENT_MF
              value: "1.5"
            - name: K_BIG
              value: "20"
            - name: K
              value: "4"
            - name: MONITOR_URL
              value: "http://image-analyzer-service:8003"
            - name: DB_URL
              value: "http://monitor-service:3200"
            - name: MANIFEST_NAME
              value: "image-analyzer"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-image-analyzer-service
spec:
  selector:
    app: ls-algorithm-image-analyzer
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002
