---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-image-analyzer
spec:
  selector:
    matchLabels:
      app: ls-algorithm-image-analyzer
  template:
    metadata:
      labels:
        app: ls-algorithm-image-analyzer
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling:development
          imagePullPolicy: Always
          ports:
            - containerPort: 7002
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "231"
            - name: COMPONENT_MF
              value: "1.5"
            - name: K_BIG
              value: "10"
            - name: K
              value: "1"
            - name: MONITOR_URL
              value: "http://attachment-manager-service:8002"
            - name: DB_URL
              value: "http://monitor-service:3200"
            - name: MANIFEST_NAME
              value: "image-analyzer"
            - name: QUEUE_NAME
              value: "imageanalyzer.queue"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "9090"
            - name: SERVICE_PORT
              value: "7002"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-image-analyzer-service
spec:
  selector:
    app: ls-algorithm-image-analyzer
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002
