---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-message-analyzer
spec:
  selector:
    matchLabels:
      app: ls-algorithm-message-analyzer
  template:
    metadata:
      labels:
        app: ls-algorithm-message-analyzer
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling:development
          imagePullPolicy: Always
          ports:
            - containerPort: 7004
          env:
            - name: SLEEP_TIME
              value: "2"
            - name: COMPONENT_MCL
              value: "300"
            - name: COMPONENT_MF
              value: "5.0"
            - name: K_BIG
              value: "10"
            - name: K
              value: "1"
            - name: MONITOR_URL
              value: "http://message-analyzer-service:8006"
            - name: MANIFEST_NAME
              value: "message-analyzer"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-message-analyzer-service
spec:
  selector:
    app: ls-algorithm-message-analyzer
  ports:
    - protocol: TCP
      port: 7004
      targetPort: 7004
