---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-message-analyzer
spec:
  selector:
    matchLabels:
      app: ls-algorithm-message-analyzer
  template:
    metadata:
      labels:
        app: ls-algorithm-message-analyzer
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling
          imagePullPolicy: Always
          ports:
            - containerPort: 7004
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "300"
            - name: COMPONENT_MF
              value: "5.0"
            - name: K_BIG
              value: "20"
            - name: K
              value: "10"
            - name: MANIFEST_NAME
              value: "message-analyzer"
            - name: METRIC_NAME
              value: "http_requests_total_message_analyzer_counter"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: SERVICE_PORT
              value: "7004"
            - name: ORACLE
              value: "false"
            - name: PREDICTIONS
              value: "16.39011111111111, 731.4803333333332, 1793.3333333333333, 3908.8888888888887, 6112.840777777778, 10026.185444444445, 16970.44955555556, 27306.48255377491, 37521.34350570191, 39721.12611588756, 26948.96564097755, 23120.532144112898, 18687.018127956995, 17460.090055555556, 15788.888888888889, 16542.006052745353, 12785.555555555555, 12968.88888888889, 4898.88888888889, 5247.777777777778"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-message-analyzer-service
spec:
  selector:
    app: ls-algorithm-message-analyzer
  ports:
    - protocol: TCP
      port: 7004
      targetPort: 7004
