---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-message-analyzer
spec:
  selector:
    matchLabels:
      app: ls-algorithm-message-analyzer
  template:
    metadata:
      labels:
        app: ls-algorithm-message-analyzer
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling
          imagePullPolicy: Always
          ports:
            - containerPort: 7004
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "300"
            - name: COMPONENT_MF
              value: "5.0"
            - name: K_BIG
              value: "20"
            - name: K
              value: "10"
            - name: MANIFEST_NAME
              value: "message-analyzer"
            - name: METRIC_NAME
              value: "http_requests_total_message_analyzer_counter"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: SERVICE_PORT
              value: "7004"
            - name: ORACLE
              value: "true"
            - name: PREDICTIONS
              value: "752, 1886, 3948, 8433, 16437, 22970, 27332, 30831, 28710, 25880, 21895, 17839, 15134, 15050, 15194, 12092, 9836, 3996, 5608, 9384"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-message-analyzer-service
spec:
  selector:
    app: ls-algorithm-message-analyzer
  ports:
    - protocol: TCP
      port: 7004
      targetPort: 7004
