apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-analyzer
spec:
  selector:
    matchLabels:
      app: message-analyzer
  template:
    metadata:
      labels:
        app: message-analyzer
    spec:
      containers:
        - name: message-analyzer
          image: lorenzobacchiani/message-analyzer
          imagePullPolicy: Always
          ports:
            - containerPort: 8006
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: MCL
              value: "120"
            - name: LIMIT
              value: "400"
            - name: BATCH
              value: "120"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: message-analyzer-service
spec:
  selector:
    app: message-analyzer
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006

