name: Build & Publish Docker images
on:
  push:
    branches:
      - development
      - refactor/remove-rabbitmq

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./parser/Dockerfile
            context: ./parser
            image: giovaz94/parser-service
          - dockerfile: ./rabbitmq/Dockerfile
            context: ./rabbitmq
            image: giovaz94/rabbitmq-service
          - dockerfile: ./entrypoint/Dockerfile
            context: ./entrypoint
            image: giovaz94/entrypoint
          - dockerfile: ./virus-scanner/Dockerfile
            context: ./virus-scanner
            image: giovaz94/virus-scanner-service
          - dockerfile: ./attachment-manager/Dockerfile
            context: ./attachment-manager
            image: giovaz94/attachment-manager-service
          - dockerfile: ./image-analyzer/Dockerfile
            context: ./image-analyzer
            image: giovaz94/image-analyzer-service
          - dockerfile: ./image-recognizer/Dockerfile
            context: ./image-recognizer
            image: giovaz94/image-recognizer-service
          - dockerfile: ./nsfw-detector/Dockerfile
            context: ./nsfw-detector
            image: giovaz94/nsfw-detector-service
          - dockerfile: ./message-analyzer/Dockerfile
            context: ./message-analyzer
            image: giovaz94/message-analyzer-service
          - dockerfile: ./local_scaling/Dockerfile
            context: ./local_scaling
            image: giovaz94/local_scaling

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}

      - name: Build and push on Docker hub
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}