apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    node:
      id: test_id
      cluster: ingress_cluster

    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: entrypoint_cluster
                    http_filters:
                      - name: envoy.filters.http.router

      clusters:
        - name: entrypoint_cluster
          connect_timeout: 0.25s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: entrypoint_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: entrypoint-service
                          port_value: 8010

    stats_sinks:
      - name: envoy.stat_sinks.prometheus
        typed_config:
          "@type": type.googleapis.com/envoy.config.metrics.v3.PrometheusSink

    stats_config:
      stats_matcher:
        inclusion_list:
          patterns:
            - prefix: "http"