apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.17.0
          ports:
            - containerPort: 9901
            - containerPort: 10000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  selector:
    app: envoy
  ports:
    - port: 80
      protocol: TCP
      targetPort: 10000
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: envoy-admin
spec:
  selector:
    app: envoy
  ports:
    - protocol: TCP
      port: 9901
      targetPort: 9901
  type: ClusterIP
